### ISSUE TITLE
Идея свободного программного обеспечения является атрибутом современного мира где все должно решаться мирным путем.

### ISSUE THREAD

**Issue by AndreyZlenko** [stop-war-in-ukraine/stop-russia-it#105]
Россия же идет против этого. Тот кто пишет строчки кода решающие какую либо проблему и делает их доступными для всех желает сделать этот мир лучше. Но он не застрахован от того что россия не будет использовать этот код в программном обеспечении военных комплексов. Простыми словами, завтра к вам прилетит русская ракета которая использует код написаный вами же. В виду этого, на мой взгляд, россия как агрессор потеряло наше доверие и какое либо право использовать наработки мирных  людей!!   
   Заберите у россии право и возможность убивать вас вашими же достижениями

**Comment by SergeiShelest** [comment]
Укропа порвало. XD

**Comment by kelp404** [comment]
りしれ供さ小？

**Comment by AnrDaemon** [comment]
Или американская ракета, использующая код, написанный вами же. Или украинская. Польская. Китайская. Юпитерианская. Альдебаранская.
Вы сами свой бред вообще читаете? Или вам на почве всеобщей истерии отказало критическое восприятие действительности?

**Comment by nokitakaze** [comment]
Хохла забыли спросить

**Comment by apoterenko** [comment]
Где ты был, друг, когда НАТО бомбило Югославию. Я был в Белграде и видел последствия этого всего. Но вам лишь бы найти в русских виновных всех ваших бед, белая горячка промытых мозгов

**Comment by zolotykh** [comment]
Код научился писать, а думать?
