### ISSUE TITLE
🇷🇺 Friends, stop the propaganda. Ukrainians bombed their own "wrong" citizens last 8 years, ~ 13k people killed and no one has worried. Now ukrainians do information war based on lies

### ISSUE THREAD

**Issue by Leikam** [stop-war-in-ukraine/stop-russia-it#125]
Everyone is against any war. But stay objective. Russia has been trying to persuade it not to start for 8 years, instead to start a dialogue with Donetsk and Lugansk, see the "Minsk Agreements". Ukraine did not do anything under the agreements to stop conflict, but continued to bomb peaceful cities - and no one was worried. It continues to this day - a photo below – a blow to the peaceful Donetsk on March 14, when 20 civilians were killed. With your "support", you value the lives of some people and do not notice how for 8 years, since 2014, the Ukrainian army has been killing residents of "dissenting" republics in Ukraine, in fact their own citizens. You were not worried about other wars - who "stands against USA" in Libya, Syria, Iraq? Or is it different and there were "good NATO guys" there? Do you think you're doing a good thing? You are being deceived, or you just don't want to know the truth. But this is russophobia and racism, and choosing the life of some at the expense of the lives of others – is nazism. Just how it is in Ukraine now - you can find a lot of evidences in the Internet, if you are really interested, i don't want to post photos with nazi symbols in ukrainian army. But now you listen to only one side and support only it, like cheap populism: after all "the strong beats the weak", but you don't look at the conflict objectively. This is wrong way and the least good thing you can do is to observe neutrality in this matter, which has not concerned you for 8 years and hardly concerns you now.

Just one of many strikes that Ukraine has been doing on Donetsk and Lugansk for 8 years.
![image](https://user-images.githubusercontent.com/1935560/158798252-af3f4287-a264-41c1-af98-98abeb4e2958.png)

**Comment by AntonNah** [comment]
Bot

**Comment by zolotykh** [comment]
> Bot

Сам ты бот

**Comment by ITDOGTOR** [comment]
Ребята, вам БЛЯТЬ, заняться нехуй!!! А как же open source вне политики? Переобулись блять?

**Comment by AntonNah** [comment]
> > Bot
> 
> Сам ты бот

Путинский хуесос детектед

**Comment by ITDOGTOR** [comment]
> > > Bot
> > 
> > 
> > Сам ты бот
> 
> Путинский хуесос детектед

Это вся твоя реплика?

**Comment by zolotykh** [comment]
> > > Bot
> > 
> > 
> > Сам ты бот
> 
> Путинский хуесос детектед

Владение словом не твой конек, да и разработчик ты видимо посредственный.

**Comment by ITDOGTOR** [comment]
> > > > Bot
> > > 
> > > 
> > > Сам ты бот
> > 
> > 
> > Путинский хуесос детектед
> 
> Владение словом не твой конек, да и разработчик ты видимо посредственный.

Не вам решать, какой я разработчик. А я ответил по факту.

**Comment by deliversolution** [comment]
> > > > > Bot
> > > > 
> > > > 
> > > > Сам ты бот
> > > 
> > > 
> > > Путинский хуесос детектед
> > 
> > 
> > Владение словом не твой конек, да и разработчик ты видимо посредственный.
> 
> Не вам решать, какой я разработчик. А я ответил по факту.

Видимо вышла ошибка, это я писал для [AntonNah](https://github.com/AntonNah)

**Comment by czettnersandor** [comment]
Personally, I would see all political content off from GitHub. It's a distraction and unnecessary. However, there are both sides of this coin, and if one side is allowed, then surely the other side should have a place as well.
