### ISSUE TITLE
Кто-то может мне обьяснить смысл запрещать гитхаб и тд в России?

### ISSUE THREAD

**Issue by Madaspe** [stop-war-in-ukraine/stop-russia-it#130]

**Comment by Madaspe** [comment]
Can someone explain to me the meaning of banning github, etc. in Russia?

**Comment by stop-war-in-ukraine** [comment]
@Madaspe А кто вам сказал о запрете? Это спецоперация по дедиджитализации IT-сектора в рф, поскольку рф может захватить интернет))
Надеюсь достаточно информативно ответил в стиле понятному гражданам россии.

**Comment by Madaspe** [comment]
Ну ответа нет?

**Comment by Madaspe** [comment]
Какой смысл в этом то?

**Comment by apoterenko** [comment]
Люди Мариуполя уже ответили по Донбасу https://www.youtube.com/watch?v=Fltyms2pVto

**Comment by apoterenko** [comment]
Смысл в том, что у них ненависть ко всему русскому. Это неизлечимо. Время все расставит на свои места
