### ISSUE TITLE
you are ignorant neofascists

### ISSUE THREAD

**Issue by Nakilon** [stop-war-in-ukraine/stop-russia-it#23]

**Comment by oleksiizabara** [comment]
Fascists are bombing Ukrainian cities at night!
Fascists have come to a foreign country and are killing Ukrainian women and children!

 Say "no" to fascism in the world! Stop russia! Stop putin!

**Comment by Nakilon** [comment]
You've just made a content for me to report the misinformation to ban your little mouth on github.

P.S.: https://www.youtube.com/watch?v=Y3w_QljRytA

**Comment by Nakilon** [comment]
> Fascists are bombing Ukrainian cities at night! Fascists have come to a foreign country and are killing Ukrainian women and children!
> Say "no" to fascism in the world! Stop russia! Stop putin!

You've just made a content for me to report the misinformation to ban your little mouth from github.

P.S.: https://www.youtube.com/watch?v=Y3w_QljRytA

**Comment by oleksiizabara** [comment]
> Thank you, you've just made a content for me to report the misinformation to ban you from github.

I live in Ukraine and I see everything with my own eyes!
Or should I close my eyes and ears like you all and trust only Lavrov?? maybe you also can attach Russia24 here or Solovyov?
