### ISSUE TITLE
Friends, we support you, but please listen to us.

### ISSUE THREAD

**Issue by estum** [stop-war-in-ukraine/stop-russia-it#31]
We aren't sitting back, we are making demonstrations, and also we keep to use the services also for protesting activity.

I urge to not exhaust protestors to an overall isolation. The informational resistance will be damaged without those services, let's look at DOXA articles: it is now hosts on github and will stay here. Otherwise we will be restricted to use only russian services, they delete protesting articles very quickly.

You suppose to do that will be done very soon by the crime government: cut us out of outer world. How it could help?

I wish peace to all!

---

Мы не сидим сложа руки, мы выходим на митинги и помимо этого продолжаем пользоваться сервисами, в том числе и для протестной деятельности.

Призываю вас не загонять митингующих в полную изоляцию, без данных инструментов будет невозможно информационное сопротивление, взгляните на материалы той же DOXA: они сейчас выложены на гитхабе, и отсюда никуда не денутся. В противном случае мы будем ограничены только российскими сервисами, которые удаляют протестные материалы на раз-два (в лучшем случае).

Вы предлагаете сделать то, что скорее всего сделает преступное правительство: отрежет нас от внешнего мира. Как это может помочь?

Всем мира!

**Comment by digiom-ceo** [comment]
Твиттер и прочие правительственные СМИ так-же удаляют неугодную информацию.
Вместо того, что бы отстраниться от всего этого, идиоты всех стран нас ввязывают в войны.

**Comment by estum** [comment]
I can't agree with the previous commenter.

**Comment by stop-war-in-ukraine** [comment]
`Статья 3 1. Носителем суверенитета и единственным источником власти в Российской Федерации является ее многонациональный народ. Народ осуществляет свою власть непосредственно, а также через органы государственной власти и органы местного самоуправления. Высшим непосредственным выражением власти народа являются референдум и свободные выборы.`

Если вам кажется, что вас чем-то ограничивают, то вы можете выходить и обращаться в органы государственной власти и органы местного самоуправления. Объединитесь! Вас много! Вы можете сделать все, что бы не быть в изоляции.

**Comment by iimetra** [comment]
It is definitely a temporary measure, until that moment when Russian government falls completely.

**Comment by estum** [comment]
We are doing all of this, please, believe.

> It is definitely a temporary measure, until that moment when Russian government falls completely.

Please, understand: we need the subject services also for protesting activity. You want take handy instruments away from us, yes, temporary, but in the moment when we need it.

**Comment by estum** [comment]
So, now I need to loose the time for explaining that it is making our resistance more harder instead of explaining actual situation to other citizens. Sorry, but it is obviosly.

**Comment by gatamar** [comment]
@estum 
Meetings are good. But IT folks contain a few percents of the overall Russian population. 

As there probably are developers among you, please push the other people to also go to the meetings. 
Turn off your marketplace sites.
Turn off your social networks.
DDoS your own government sites.
Shutdown your mobile apps.

Please note, all of this is an informational war, and a direct risk to your life is not higher than going to the meetings, maybe even lower.

Please use all the available non-violent ways to force all people to go out. This tries to force you, and only you can force the others in your country.

**Comment by estum** [comment]
@gatamar Please keep for us a possibility to do that and we all will win surely, but it is important to support each other instead of making our part of job harder only because now we are locating here, inside, closely for the common enemy.

I say again: please hear us, the last protestors inside! A lot of our fellows, police and of course government are already trying to mute us, but we are keeping to tell. Don't be the next who ignore our words.

**Comment by estum** [comment]
This repo can't force us more, we are already forced by the terrible events, but that repo is mostly demotivating, honestly. Looks like nobody want to hear but somebody want to throw the duty on the locals only.

And I am not joking: some devs that were protested when saw that repo thought: "fuck this, they've also thrown us alone". Not so effectively, is it?

**Comment by iHaiduk** [comment]
If you are left without these resources, then your actions will be more radical and uncontested. You yourself say that the IT sector cannot cope with propaganda, but we want to disable the ability to further promote it. Perhaps this will affect the small number of people who collect rallies, but it will hit those who propagate and do not want to do anything more. This is a forced measure, because. at the expense of all the people of the Russian Federation, people in Ukraine are dying. They came to our house with a war.
Are you asking us to take pity on you while people are dying? This is true?
It is up to you to live in peace with the world's resources or to be alone in war.

**Comment by estum** [comment]
@iHaiduk You are hear nothing of I tried to tell you. 

Again: this is one of instruments to fight against the propaganda. Why do you want to left to us less instruments to use?

**Comment by gatamar** [comment]
@estum 
> Why do you want to left to us less instruments to use?

Because some of you may decide not to protest, and continue work and make money, taxes from which are indirectly killing Ukrainians now.
_So it's seems better to leave you only with the Telegram, or with the Signal app_ (if you say that Telegram is government-controlled).
_Just shut down all the possible russian IT products and either leave the country or protect_. If all IT folks will be forced to do this, it will be more effective than if VK/Yandex/other product will continue their work. _And these russian products use some the package managers, right?_

**Comment by estum** [comment]
Remember, russian government propaganda has long tentacles and skilled to manipulate of  social minds: be aware! I don't want to tell that this repo is sponsored by them, but it could be triggered by them. They always play on our anger and believes. This repo looks like the public activity for the public resonance and so? The repo's founder wrote a couple of words, hyped on a **rational** fear of the whole world and is it what we are really need? This action can have a destructive aftereffect on our protesting actions. 

@iHaiduk I wrote nothing about pity on me, why did you thought so? I asked to hear us and not to make our resistance more harder.

**Comment by stop-war-in-ukraine** [comment]
@estum Please show how you use these tools and their result. Show videos, show resources, show news, show what really works.
We have already heard about "they are not there". We are waiting for something more than your words that are worthless. You have a government, turn to it for help! Do not call online, because you are not heard there!

**Comment by estum** [comment]
@gatamar and what about rest of us who have been protesting for an already 8 years? Is it worth to make their protesting process more harder?

@stop-war-in-ukraine Why are you extrapolating on everybody? Are you asking me to throw off my activity now and find proofs that you will estimate enough or not? Please don't put sticks into wheels of local protestors, it is not what we all want today.

**Comment by estum** [comment]
@iHaiduk please not include me to "them", who are making that terrible things. I am a pacifist for the whole life.

Just imagine: you are fighting against the widespread ignorance in your country, everyday receives a lot of threats, and what you receive from the like-minded people abroad that country? "You are doing bad and guilt anyway, let's make your tasks harder now"

So, I tried.

**Comment by digiom-ceo** [comment]
@estum [estum](https://github.com/estum) я тоже пацифист, но меня уже несколько раз пытались убить украинцы.

Ты им ничего не докажешь, их обработала пропаганда. Причем источник пропаганды сейчас делит между собой 630млр. руб. Команду Челси, множества яхт и других ценностей. Войну начали те, кому это выгодно. Участники войны никогда не будут иметь выгоду и РФ это знает.
