### ISSUE TITLE
Go to other FOSS/OS companies?

### ISSUE THREAD

**Issue by ItzSwirlz** [stop-war-in-ukraine/stop-russia-it#36]
Not sure on whether people would be happy with this, but maybe have other tech companies/groups intervene such as

Canonical
Red Hat

I'm not opening a PR as this opens other doors (Ubuntu, Debian, Fedora), so thoughts?

**Comment by iimetra** [comment]
sounds like good idea

**Comment by digiom-ceo** [comment]
Free software cannot be blocked by anyone. Especially because of the propaganda of the Nazis from Ukraine.

**Comment by ItzSwirlz** [comment]
> Free software cannot be blocked by anyone. Especially because of the propaganda of the Nazis from Ukraine.

Well there can be people who speak out against it. Of course, contributors still welcome (since its not the peoples fault) but condemn them.

One idea could be to block downloads in Russia.

**Comment by digiom-ceo** [comment]
> One idea could be to block downloads in Russia.

How about a lockdown for America that killed 3 million people in Iraq?

[https://en.wikipedia.org/wiki/Casualties_of_the_Iraq_War](https://en.wikipedia.org/wiki/Casualties_of_the_Iraq_War)

**Comment by Anderwerty** [comment]
@digiom-ceo . It seems that the russian ship forgot to take you!

**Comment by jsisaev1** [comment]
> > Free software cannot be blocked by anyone. Especially because of the propaganda of the Nazis from Ukraine.
> 
> Well there can be people who speak out against it. Of course, contributors still welcome (since its not the peoples fault) but condemn them.
> 
> One idea could be to block downloads in Russia.

you must block your anus like roscomnadzor (mass media regulator) wanted to block Telegram (and it's banned 127.0.0.1 instead of this messanger).

the main idea to ban, kill and burn anyone who want to discriminate others.

**Comment by ItzSwirlz** [comment]
Ok. I'm closing this issue. Escalated way too far, way too quickly. And I'm requesting this gets locked.

I won't open a PR as I am an ubuntu contributor and I don't know how this would work with Ubuntu Code of Conduct, although its Canonical. However, Red Hat is a good idea.
