### ISSUE TITLE
Open Source: lisence

### ISSUE THREAD

**Issue by cfcfty** [stop-war-in-ukraine/stop-russia-it#45]
By this call you are contradicting the open source paradigm.  Maybe we should not carry politics into our environment?
P. S. See: https://www.gnu.org/philosophy/free-sw.en.html

**Comment by digiom-ceo** [comment]
This philosophy only works when it benefits the dollar and NATO dependent countries. They spit on the whole world and unleash wars, as they are now. They incited neo-Nazis, Hitler's accomplices, fomented war among normal people.
Under the guise they took away all the acquired wealth, namely 630 billion dollars from the National Wealth Fund of the Russian Federation. Less than $500 million in credit was allocated to start the war. These 500 million residents of Ukraine will have to be returned, this is not a gift.

**Comment by oleksiizabara** [comment]
это лицензия для цивилизованного мира! фашистская россия к таковым уже увы не относится!

**Comment by jsisaev1** [comment]
this codemonkeys want to use double standard policy.
and they want to kill every Russian.
they (those who contributed, forked or starred this repo) are Nazis

**Comment by jsisaev1** [comment]
> это лицензия для цивилизованного мира! фашистская россия к таковым уже увы не относится!

о, началось, "вынипанимаитиытадругоэ!!!111адыадын"
тупые, алчные  воры (укргаз, укрнафта и др) должны быть забанены везде где можно.

**Comment by oleksiizabara** [comment]
>and they want to kill every Russian.

мы этого не хотим! хотим чтобы вы поняли насколько презираем цивилизованным миром ваш фашисткий режим! насколько вы бесполезны в нынешней россии без всего, что предоставляет вам ненавистный запад! и вы и сами жто понимаете раз так взбудоражились!

приезжайте к нам и сможете честно вести бизнес со всем миром дальше! добро пожаловать в Украину! 

>тупые, алчные воры (укргаз, укрнафта и др) должны быть забанены везде где можно.

ну так забань! че сидишь-то

**Comment by cfcfty** [comment]
I asked you about how you want to restrict open source, although its license does not allow this.

 And all of you have gone into politics and mutual insults.  

GitHub is out of politics!

**Comment by jsisaev1** [comment]
> > and they want to kill every Russian.
> 
> мы этого не хотим! хотим чтобы вы поняли насколько презираем цивилизованным миром ваш фашисткий режим! насколько вы бесполезны в нынешней россии без всего, что предоставляет вам ненавистный запад! и вы и сами жто понимаете раз так взбудоражились!
> 
> приезжайте к нам и сможете честно вести бизнес со всем миром дальше! добро пожаловать в Украину!
> 
> > тупые, алчные воры (укргаз, укрнафта и др) должны быть забанены везде где можно.
> 
> ну так забань! че сидишь-то

програмбайтер, целуй мой сапог.
зелебоба капитулирует, а европа распадется из-за цен на сырье.
штаты и китай скупят все по дешевке, а вы будете дальше по норам сидеть, потому что вы спустили страну в унитаз и дали бразды правления пиздурку, который предсказал судьбу страны еще 15 лет назад (путин вайна начинать, я какать и ролик про регионы украины, где он не понимает где реальная историческая украина)

**Comment by jsisaev1** [comment]
> I asked you about how you want to restrict open source, although its license does not allow this.
> 
> And all of you have gone into politics and mutual insults.
> 
> GitHub is out of politics!

I think that creator and contributors of this repository are members of terroristic organisation of LGBT.
organisation in above want to ban all non-black nations on the earth and want to grab all money over the world because they have poor mind.

**Comment by Nakilon** [comment]
> all of you have gone into politics and mutual insults

Why are you surprised? The insane dude is a neofascist.
https://imgur.com/a/IrbvgbE

**Comment by Nakilon** [comment]
> all of you have gone into politics and mutual insults

Why are you surprised? The insane dude is a neofascist.
https://imgur.com/a/IrbvgbE
They are those who started the war 8 years ago and why the Russia started the military operation to end the war. They are mad because Russia is going to end the war and genocide that Poroshenko started and Zelensky continued.
