### ISSUE TITLE
Also stop sharing VPN connections from their IPs

### ISSUE THREAD

**Issue by kurtiev** [stop-war-in-ukraine/stop-russia-it#7]

**Comment by jsisaev1** [comment]
ban Ukraine in RIPE NCC and revoke all AS from this contry.
also all IT giants and other hardware and software vendors must ban Ukraine from technologies and fire from job all Ukranians in other countries and send them to Unkraine with permanent lifetime ban for leaving this country

**Comment by greatbody** [comment]
We love America even if it bombs civilians everywhere;
We condemn Russia even if its response is forced by America.

**Comment by greatbody** [comment]
Actually, the most advanced VPNs are managed by Chinese, why not ban China IP, 5555555

**Comment by jsisaev1** [comment]
переможный зрадовец, тебе давно ГРАДом не поливали? может быть, буратино тебе устроит солнцепек? или может быть, тебе надо подарить букет гиацинтов с тюльпанами? или васильков на подносе? также могу предложить тебе ураганный смерч с пионами и гвоздики. тетушка Нона может предложить тебе куст акации в снегу и тунгуску.

ЗЫ. Пидорасам не нравится права, они её удаляют.

**Comment by greatbody** [comment]
Why not block Chinese IP range, I can share.

Because China has the most advanced tech on setting up VPN.

**Comment by kurtiev** [comment]
ANY company that provides VPN services should prevent their services for russian IP's, untill war is finished in Ukraine. That we meant.

**Comment by undying** [comment]
So you want to cut off the Russians from outside information? This is to the advantage of the Russian government, which wants to keep its people in the dark.
There is no need to confuse Russians and Putin. Now you are not doing badly to the government of the Russian Federation, but to ordinary people, that is, you are no better than the Putin.

**Comment by kurtiev** [comment]
"ordinary people" just go out, stop him. Don't you see what is going on in my country?
How should we react to this war from your perspective? Keep silent, as you do?
Again, until the war isn't finished, we will do everything that is needed. Please understand and react to your government.

**Comment by undying** [comment]
Do what you think is necessary. I just want to say that what you are doing is stirring up xenophobia, not influencing the government. Ordinary people are already taking to the streets protesting against the war, how do you help them with your actions? Instead, you are equating all people with Putin. 

I'm from Belarus, and I've been out on the streets for many years, alas, it didn't help. But when my people asked their neighbors not to recognize Lukashenko as legitimate, where were you? Zelensky sent Gordon to Belarus to interview Lukashenko as the president of Belarus, so it's not for you to tell me what I should do and how to behave. I am very sorry that the war has come to your lands. I strongly condemn the actions of both Putin and the hated by me Lukashenko. But embedding malicious code in our programs nor blocking VPN does not impact them in any way. It doesn't affect the outcome of the war, but it incites hatred between ordinary people like you and me.
