### ISSUE TITLE
Add maven central artifactory to block package distribution for Java programs 

### ISSUE THREAD

**Issue by iimetra** [stop-war-in-ukraine/stop-russia-it#9]
https://mvnrepository.com/repos/central
https://repo.maven.apache.org/maven2/

**Comment by stop-war-in-ukraine** [comment]
Cool! Please, make Pull requests

**Comment by iimetra** [comment]
https://github.com/stop-war-in-ukraine/stop-russia-it/pull/13

**Comment by iimetra** [comment]
merged
